#!/bin/bash
# Idea: https://nickcharlton.net/posts/debian-ubuntu-dynamic-motd.html - thanks !

# http://stackoverflow.com/questions/4332478/read-the-current-text-color-in-a-xterm/4332530#4332530
# fancy text information {{{
BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
LIME_YELLOW=$(tput setaf 190)
POWDER_BLUE=$(tput setaf 153)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)
BLINK=$(tput blink)
REVERSE=$(tput smso)
UNDERLINE=$(tput smul)
# }}}


cat <<STIITTOOLBOX
--------------------------------------------------------------------------------
.       ____ _____ ___     ___ _____   _____           _ _                     .
.      / ___|_   _|_ _|   |_ _|_   _| |_   _|__   ___ | | |__   _____  __      .
.      \___ \ | |  | |_____| |  | |     | |/ _ \ / _ \| | '_ \ / _ \ \/ /      .
.       ___) || |  | |_____| |  | |     | | (_) | (_) | | |_) | (_) >  <       .
.      |____/ |_| |___|   |___| |_|     |_|\___/ \___/|_|_.__/ \___/_/\_\\      .
.                                       v0.8   <stiitdev@groupes.epfl.ch>      .
.                      https://github.com/epfl-sti/cluster.coreos.toolbox      .
.                 https://hub.docker.com/r/epflsti/cluster.coreos.toolbox      .
--------------------------------------------------------------------------------
STIITTOOLBOX
echo "${CYAN}                   Note: this toolbox is poshed up by STI-IT${NORMAL}"

[ -r /etc/lsb-release ] && . /etc/lsb-release
if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
        # Fall back to using the very slow lsb_release utility
        DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

printf "\n"
printf " Welcome to %s running on %s (kernel %s)\n" "${BLUE}$(hostname)${NORMAL}" "$DISTRIB_DESCRIPTION" "$(uname -r)"
printf "\n"

[ -f /etc/motd.tail ] && cat /etc/motd.tail || true
